'use client';

// The visible lesson player: a REAL agent-generated multi-scene lesson, playing on the
// one clock. Board writing + pointer + code reveal + subtitles are all clock-driven;
// scenes auto-advance (onEnded -> next), like a course player. No audio yet (TTS blocked),
// so narration shows as synced subtitles — the lesson is fully watchable.

import { useEffect, useMemo, useRef, useState } from 'react';

import { boardStateAt } from '../../../lib/playback/engine/action-engine.js';
import { createManualClock } from '../../../lib/playback/clock/manual-clock.js';
import { renderBoardSvg } from '../../../packages/@forever/renderer/src/board-svg.js';
import lesson from './generated-lesson.json';

export default function LessonPage() {
  const [sceneIndex, setSceneIndex] = useState(0);
  const [tMs, setTMs] = useState(0);
  const [playing, setPlaying] = useState(false);
  const clockRef = useRef(null);
  if (!clockRef.current) clockRef.current = createManualClock();
  const clock = clockRef.current;

  const scene = lesson.scenes[sceneIndex];
  const durationMs = scene.durationMs;

  useEffect(() => {
    let frame;
    const tick = () => {
      const next = Math.min(clock.currentTimeMs(), durationMs);
      setTMs(next);
      if (next >= durationMs && clock.isPlaying()) {
        clock.pause();
        if (sceneIndex < lesson.scenes.length - 1) {
          setSceneIndex((index) => index + 1); // auto-advance
        } else {
          setPlaying(false);
        }
      }
      frame = requestAnimationFrame(tick);
    };
    frame = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(frame);
  }, [clock, durationMs, sceneIndex]);

  // When the scene changes, reset the clock (and keep playing through the lesson).
  useEffect(() => {
    clock.seek(0);
    setTMs(0);
    if (playing) clock.play();
  }, [sceneIndex]); // eslint-disable-line react-hooks/exhaustive-deps

  const state = useMemo(() => boardStateAt(scene.timeline, tMs), [scene, tMs]);
  const svg = useMemo(() => renderBoardSvg(scene, state), [scene, state]);
  const subtitle = state.activeSpeech
    ? scene.voiceLines.find((line) => line.id === state.activeSpeech)?.text
    : '';

  const togglePlay = () => {
    if (clock.isPlaying()) {
      clock.pause();
      setPlaying(false);
    } else {
      if (clock.currentTimeMs() >= durationMs) clock.seek(0);
      clock.play();
      setPlaying(true);
    }
  };

  const goToScene = (index) => {
    setSceneIndex(index);
    clock.seek(0);
    setTMs(0);
  };

  return (
    <main style={{ display: 'flex', gap: 20, maxWidth: 1200, margin: '20px auto', padding: '0 16px' }}>
      <aside style={{ width: 240, flexShrink: 0 }}>
        <div style={{ fontWeight: 700, fontSize: 18, marginBottom: 4 }}>{lesson.lessonTitle}</div>
        <div style={{ fontSize: 12, color: '#8a6d3b', marginBottom: 12 }}>
          {lesson.scenes.length} scenes · generated by the agent society
        </div>
        {lesson.scenes.map((s, index) => (
          <button
            key={s.sceneId}
            onClick={() => goToScene(index)}
            style={{
              display: 'block',
              width: '100%',
              textAlign: 'left',
              padding: '10px 12px',
              marginBottom: 6,
              borderRadius: 8,
              border: '1px solid #e8ddc9',
              background: index === sceneIndex ? '#fdeaa7' : '#fff',
              cursor: 'pointer',
            }}
          >
            <div style={{ fontSize: 13, fontWeight: 600 }}>
              {index + 1}. {s.title}
            </div>
            <div style={{ fontSize: 11, color: '#8a6d3b' }}>{(s.durationMs / 1000).toFixed(0)}s</div>
          </button>
        ))}
      </aside>

      <section style={{ flex: 1 }}>
        <div
          style={{ border: '1px solid #e8ddc9', borderRadius: 12, overflow: 'hidden', background: '#fdf8f0' }}
          dangerouslySetInnerHTML={{ __html: svg }}
        />
        <div style={{ minHeight: 30, padding: '10px 4px', color: '#7a4a12', fontStyle: 'italic', fontSize: 15 }}>
          {subtitle}
        </div>
        <div style={{ display: 'flex', gap: 12, alignItems: 'center' }}>
          <button onClick={togglePlay} style={{ padding: '8px 22px', fontSize: 16 }}>
            {playing ? 'Pause' : 'Play'}
          </button>
          <span style={{ fontVariantNumeric: 'tabular-nums', fontSize: 13 }}>
            Scene {sceneIndex + 1}/{lesson.scenes.length} · {(tMs / 1000).toFixed(1)}s / {(durationMs / 1000).toFixed(1)}s
          </span>
          <input
            type="range"
            min="0"
            max={durationMs}
            value={tMs}
            onChange={(event) => {
              clock.seek(Number(event.target.value));
              setTMs(Number(event.target.value));
            }}
            style={{ flex: 1 }}
          />
        </div>
      </section>
    </main>
  );
}
