"use strict";
require("dotenv").config({ path: require("path").resolve(__dirname, "../.env") });
const svc = require("./services/googleAgent/stage1ConceptTree.service.js");
const mongoose = require("mongoose");
const RES = "glt_resource_1780558985921_5f1ea0e3";
(async () => {
  console.log("Regenerating tree (multimodal + vision-truth evidence)...");
  const out = await svc.buildConceptTree({ ownerKey: "jana_test", resourceId: RES, body: {}, context: {} });
  const tid = (out.tree||out).treeId || out.treeId;
  await mongoose.connect(process.env.MONGODB_URI||process.env.MONGO_URI,{dbName:process.env.MONGODB_DATABASE,serverSelectionTimeoutMS:15000});
  const doc = await mongoose.connection.db.collection("live_tutor_concept_trees").findOne({treeId:tid});
  const nodes=(doc&&doc.nodes)||[];
  const types={}; nodes.forEach(n=>types[n.nodeType]=(types[n.nodeType]||0)+1);
  const covered=new Set(); nodes.forEach(n=>(n.pageRefs||[]).forEach(p=>covered.add(Number(p))));
  const missing=[]; for(let p=1;p<=22;p++) if(!covered.has(p)) missing.push(p);
  console.log("\n===== SAVED TREE =====");
  console.log("treeId:", tid, "| nodes:", nodes.length, "| nodeTypes:", JSON.stringify(types));
  console.log("coveredPages:", [...covered].sort((a,b)=>a-b).join(","));
  console.log("MISSING PAGES:", missing.join(",")||"NONE  ✅ all 22 pages covered");
  await mongoose.disconnect(); process.exit(0);
})().catch(e => { console.error("ERR:", e.message); process.exit(1); });
