'use client';

// The reusable course player: takes a lesson (from generation or storage) and plays it.
// Route pages (app/course/[id], app/dev/lesson) are thin wrappers that supply the lesson.

import { useLessonClock } from './use-lesson-clock.js';
import { StagePresenter } from '../panels/stage-presenter.js';

export function LessonPlayer({ lesson }) {
  const player = useLessonClock(lesson.scenes);
  const { scene, sceneIndex, tMs, durationMs, playing } = player;

  return (
    <main style={{ display: 'flex', gap: 20, maxWidth: 1200, margin: '20px auto', padding: '0 16px' }}>
      <aside style={{ width: 240, flexShrink: 0 }}>
        <div style={{ fontWeight: 700, fontSize: 18, marginBottom: 4 }}>{lesson.lessonTitle}</div>
        <div style={{ fontSize: 12, color: '#8a6d3b', marginBottom: 12 }}>
          {lesson.scenes.length} scenes · generated by the agent society
        </div>
        {lesson.scenes.map((s, index) => (
          <button
            key={s.sceneId}
            onClick={() => player.goToScene(index)}
            style={{
              display: 'block',
              width: '100%',
              textAlign: 'left',
              padding: '10px 12px',
              marginBottom: 6,
              borderRadius: 8,
              border: '1px solid #e8ddc9',
              background: index === sceneIndex ? '#fdeaa7' : '#fff',
              cursor: 'pointer',
            }}
          >
            <div style={{ fontSize: 13, fontWeight: 600 }}>
              {index + 1}. {s.title}
            </div>
            <div style={{ fontSize: 11, color: '#8a6d3b' }}>{(s.durationMs / 1000).toFixed(0)}s</div>
          </button>
        ))}
      </aside>

      <section style={{ flex: 1 }}>
        {player.audioUrl && (
          <audio ref={player.audioRef} src={player.audioUrl} preload="auto" key={player.audioUrl} />
        )}
        <StagePresenter scene={scene} tMs={tMs} title={scene.title} />
        <div style={{ display: 'flex', gap: 12, alignItems: 'center' }}>
          <button onClick={player.togglePlay} style={{ padding: '8px 22px', fontSize: 16 }}>
            {playing ? 'Pause' : 'Play'}
          </button>
          <span style={{ fontVariantNumeric: 'tabular-nums', fontSize: 13 }}>
            Scene {sceneIndex + 1}/{lesson.scenes.length} · {(tMs / 1000).toFixed(1)}s / {(durationMs / 1000).toFixed(1)}s
          </span>
          <input
            type="range"
            min="0"
            max={durationMs}
            value={tMs}
            onChange={(event) => player.seek(Number(event.target.value))}
            style={{ flex: 1 }}
          />
        </div>
      </section>
    </main>
  );
}
