'use client';

// The course shell — what makes a lesson FEEL like a real course (Udemy/Coursera anatomy:
// persistent episode sidebar with per-item checkmarks + duration, visible progress math,
// real player chrome with speed/skip/fullscreen, and a scene timeline strip). Playback
// logic lives in useLessonClock; this component is pure presentation around it.
// Progress persists per lesson in localStorage so "continue where you left off" is real.

import { useEffect, useRef, useState } from 'react';

import { useLessonClock } from './use-lesson-clock.js';
import { StagePresenter } from '../panels/stage-presenter.js';

const UI = {
  text: '#3a2e22',
  muted: '#8a6d3b',
  border: '#e8ddc9',
  card: '#fffdf7',
  accent: '#e8604c',
  accentSoft: '#fdeaa7',
  done: '#3f9d63',
};

const fmt = (ms) => {
  const s = Math.max(0, Math.round(ms / 1000));
  return `${Math.floor(s / 60)}:${String(s % 60).padStart(2, '0')}`;
};

const SPEEDS = [1, 1.25, 1.5, 1.75, 0.75];

export function LessonPlayer({ lesson }) {
  const player = useLessonClock(lesson.scenes);
  const { scene, sceneIndex, tMs, durationMs, playing } = player;
  const stageRef = useRef(null);
  const progressKey = `forever:progress:${lesson.sourcePackId}`;
  const [completed, setCompleted] = useState(() => new Set());

  // Progress is per-user, per-browser — hydrate after mount (SSR has no localStorage).
  useEffect(() => {
    try {
      setCompleted(new Set(JSON.parse(localStorage.getItem(progressKey) || '[]')));
    } catch { /* corrupted store -> start fresh */ }
  }, [progressKey]);

  // A scene watched to its end is complete — the checkmark is EARNED, not decorative.
  useEffect(() => {
    if (tMs < durationMs - 120 || completed.has(scene.sceneId)) return;
    const next = new Set(completed).add(scene.sceneId);
    setCompleted(next);
    try { localStorage.setItem(progressKey, JSON.stringify([...next])); } catch { /* private mode */ }
  }, [tMs, durationMs, scene.sceneId, completed, progressKey]);

  // Keyboard: space = play/pause, arrows = ±10s (unless typing in an input).
  useEffect(() => {
    const onKey = (e) => {
      if (/^(INPUT|TEXTAREA|SELECT)$/.test(e.target.tagName)) return;
      if (e.code === 'Space') { e.preventDefault(); player.togglePlay(); }
      if (e.code === 'ArrowRight') player.skip(10_000);
      if (e.code === 'ArrowLeft') player.skip(-10_000);
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [player]);

  const totalMs = lesson.scenes.reduce((n, s) => n + (s.durationMs || 0), 0);
  const pct = Math.round((completed.size / lesson.scenes.length) * 100);
  let stripOffset = 0;

  return (
    <div style={{ minHeight: '100vh', color: UI.text }}>
      {/* ---- header ---- */}
      <header style={{ display: 'flex', alignItems: 'center', gap: 14, padding: '14px 24px', borderBottom: `1px solid ${UI.border}`, background: UI.card }}>
        <a href="/" style={{ display: 'flex', alignItems: 'center', gap: 8, textDecoration: 'none', color: UI.text }}>
          <span style={{ width: 30, height: 30, borderRadius: 9, background: UI.accent, color: '#fff', display: 'grid', placeItems: 'center', fontWeight: 800 }}>F</span>
          <span style={{ fontWeight: 800, fontSize: 17 }}>Forever <span style={{ fontWeight: 500, fontSize: 12, color: UI.muted }}>AI Tutor</span></span>
        </a>
        <div style={{ marginLeft: 18, minWidth: 0 }}>
          <div style={{ fontWeight: 700, fontSize: 15, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{lesson.lessonTitle}</div>
          <div style={{ fontSize: 12, color: UI.muted }}>Scene {sceneIndex + 1} of {lesson.scenes.length} · {scene.title}</div>
        </div>
        <div style={{ marginLeft: 'auto', fontSize: 12, color: UI.muted, whiteSpace: 'nowrap' }}>
          {lesson.voiced ? 'voiced by the agent society' : 'generated by the agent society'}
        </div>
      </header>

      <main style={{ display: 'flex', gap: 18, maxWidth: 1360, margin: '18px auto', padding: '0 18px', alignItems: 'flex-start' }}>
        {/* ---- episode sidebar ---- */}
        <aside style={{ width: 280, flexShrink: 0, background: UI.card, border: `1px solid ${UI.border}`, borderRadius: 14, padding: 16 }}>
          <div style={{ fontWeight: 800, fontSize: 15, marginBottom: 2 }}>{lesson.lessonTitle}</div>
          <div style={{ fontSize: 12, color: UI.muted, marginBottom: 10 }}>{lesson.scenes.length} scenes · {fmt(totalMs)} total</div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 14 }}>
            <div style={{ flex: 1, height: 7, borderRadius: 4, background: '#f0e6d2' }}>
              <div style={{ width: `${pct}%`, height: '100%', borderRadius: 4, background: UI.accent, transition: 'width 0.3s' }} />
            </div>
            <span style={{ fontSize: 12, fontWeight: 700, color: UI.muted }}>{pct}%</span>
          </div>

          {lesson.scenes.map((s, index) => {
            const active = index === sceneIndex;
            const isDone = completed.has(s.sceneId);
            return (
              <button
                key={s.sceneId}
                onClick={() => player.goToScene(index)}
                style={{
                  display: 'flex', alignItems: 'center', gap: 10, width: '100%', textAlign: 'left',
                  padding: '10px 10px', marginBottom: 6, borderRadius: 10, cursor: 'pointer',
                  border: `1px solid ${active ? UI.accent : UI.border}`,
                  background: active ? '#fdece8' : '#fff',
                }}
              >
                <span style={{
                  width: 22, height: 22, borderRadius: '50%', flexShrink: 0, display: 'grid', placeItems: 'center',
                  fontSize: 12, fontWeight: 700,
                  background: isDone ? UI.done : active ? UI.accent : '#f0e6d2',
                  color: isDone || active ? '#fff' : UI.muted,
                }}>
                  {isDone ? '✓' : index + 1}
                </span>
                <span style={{ minWidth: 0 }}>
                  <span style={{ display: 'block', fontSize: 13, fontWeight: 600, lineHeight: 1.25 }}>{s.title}</span>
                  <span style={{ fontSize: 11, color: UI.muted }}>{fmt(s.durationMs)}{s.pedagogicalRole ? ` · ${s.pedagogicalRole}` : ''}</span>
                </span>
              </button>
            );
          })}
        </aside>

        {/* ---- stage + controls + timeline strip ---- */}
        <section style={{ flex: 1, minWidth: 0 }}>
          {player.audioUrl && (
            <audio ref={player.audioRef} src={player.audioUrl} preload="auto" key={player.audioUrl} />
          )}
          <div ref={stageRef} style={{ background: UI.card, border: `1px solid ${UI.border}`, borderRadius: 14, overflow: 'hidden' }}>
            <StagePresenter scene={scene} tMs={tMs} title={scene.title} setHold={player.setHold} />
          </div>

          {/* controls bar */}
          <div style={{ display: 'flex', gap: 12, alignItems: 'center', background: UI.card, border: `1px solid ${UI.border}`, borderRadius: 14, padding: '10px 16px', marginTop: 12 }}>
            <button onClick={player.togglePlay} aria-label={playing ? 'Pause' : 'Play'}
              style={{ width: 44, height: 44, borderRadius: '50%', border: 'none', background: UI.accent, color: '#fff', fontSize: 17, cursor: 'pointer' }}>
              {playing ? '❚❚' : '▶'}
            </button>
            <button onClick={() => player.skip(-10_000)} title="Back 10s" style={chip()}>−10s</button>
            <button onClick={() => player.skip(10_000)} title="Forward 10s" style={chip()}>+10s</button>
            <span style={{ fontVariantNumeric: 'tabular-nums', fontSize: 13, color: UI.muted, whiteSpace: 'nowrap' }}>
              {fmt(tMs)} / {fmt(durationMs)}
            </span>
            <input
              type="range" min="0" max={durationMs || 1} value={Math.min(tMs, durationMs)}
              onChange={(e) => player.seek(Number(e.target.value))}
              style={{ flex: 1, accentColor: UI.accent }}
            />
            <button
              onClick={() => player.setRate(SPEEDS[(SPEEDS.indexOf(player.rate) + 1) % SPEEDS.length])}
              title="Playback speed" style={chip({ minWidth: 52 })}>
              {player.rate}x
            </button>
            <button
              onClick={() => (document.fullscreenElement ? document.exitFullscreen() : stageRef.current?.requestFullscreen())}
              title="Fullscreen" style={chip()}>
              ⛶
            </button>
          </div>

          {/* scene timeline strip */}
          <div style={{ display: 'flex', gap: 10, overflowX: 'auto', padding: '12px 2px 4px' }}>
            {lesson.scenes.map((s, index) => {
              const startMs = stripOffset;
              stripOffset += s.durationMs || 0;
              const active = index === sceneIndex;
              return (
                <button
                  key={s.sceneId}
                  onClick={() => player.goToScene(index)}
                  style={{
                    flexShrink: 0, width: 190, textAlign: 'left', padding: '10px 12px', borderRadius: 12, cursor: 'pointer',
                    border: `2px solid ${active ? UI.accent : UI.border}`,
                    background: active ? '#fdece8' : '#fff',
                  }}
                >
                  <div style={{ fontSize: 12, fontWeight: 700, marginBottom: 3 }}>{index + 1}. {s.title}</div>
                  <div style={{ fontSize: 11, color: UI.muted }}>{fmt(startMs)} – {fmt(startMs + (s.durationMs || 0))}</div>
                </button>
              );
            })}
          </div>
        </section>
      </main>
    </div>
  );
}

function chip(extra = {}) {
  return {
    padding: '7px 12px', borderRadius: 9, border: `1px solid ${UI.border}`, background: '#fff',
    fontSize: 12, fontWeight: 700, color: UI.text, cursor: 'pointer', ...extra,
  };
}
