// Per-renderHint contract guides (one job: the rules each focused object call sees —
// ONLY its own). Narrow contract per call is the whole point of decomposed generation.

export const HINT_GUIDES = Object.freeze({
  text: 'content is a short STRING (a title or a compact note). A pure title/heading may add "decorative": true.',
  list: 'content is {"items": ["...", "..."]} — 2-5 short, concrete points.',
  callout: 'content is {"variant": one of mistake/checkpoint/recap/tip/analogy/insight, "title"?: "...", "body": "..." } — body is the teaching text.',
  quiz: `content is ONE of three kinds — pick the kind that proves understanding for THIS scene:
MCQ: {"question","choices":["...", "..."] (2-4),"answerIndex":<0-based>,"explanation":"why right"} — quick checkpoint with concrete values.
DESCRIPTIVE: {"kind":"descriptive","question","scenario":"concrete situation with real values","modelAnswer":"detailed worked answer","rubricPoints":["...", "..."] (2-6)} — the student solves in their own words.
TEACH-BACK: {"kind":"teach_back","question":"what to explain","audience":"who they teach (a younger sibling / a new teammate)","dimensions":["correctness","no unexplained jargon","gives a concrete example","says WHY it matters"] (2-5),"modelExplanation":"the rewritten teacher-grade explanation ≥80 chars"} — understanding proven by TEACHING; best on recap scenes and after the hardest idea.`,
  math: 'content is {"latex": "E = mc^2"} for one formula, or {"steps": [{"latex": "...", "note": "why this step"}]} for a derivation — real LaTeX, no prose inside latex.',
  table: 'content is {"columns": ["..."], "rows": [{"label": "...", "values": ["one per column"]}]} — the label column is implicit (never repeat the label as a column); EVERY cell filled with real text.',
  chart: `content is {"xAxis":{"label","min","max"},"yAxis":{"label","min","max"},"series":[{"id","label","points":[[x,y],...],"style"?:"solid|dashed|ghost|scatter"}],"annotations"?:[{"type":"point","x","y","label"}|{"type":"vline","x"}|{"type":"hline","y"}|{"type":"arrow","from":[x,y],"to":[x,y],"label"?}|{"type":"region","x1","x2","label"?}]}.
Every point INSIDE the axis ranges; every series labeled; a SHIFT keeps the old curve as style "ghost" with the same id stem ("demand_old"/"demand") plus an arrow annotation; name equilibria with "point" annotations; 2-6 series; never an empty template.
style "scatter" = data POINTS with no connecting line (a dataset, residuals, outliers) — a scatter point may carry a class tag: [x, y, "spam"]. Teach ML the Ng way: one scatter series per class (real example values) FIRST, then the boundary/curve as its own solid series through them.`,
  diagram: `content is ONE of: {"diagramType":"grid","rows":[[1,1,1],[1,2,3]],"rowLabels"?,"colLabels"?,"highlight"?:[[r,c]]} (a DP table / matrix / board — ALWAYS this for 2D tables, never a graph of coordinate nodes) | {"diagramType":"flowchart","steps":[...]} | {"diagramType":"cycle","steps":[...]} | {"diagramType":"tree","root":{...}} | {"diagramType":"comparison","columns":[...],"rows":[{"label","values"}]} | {"diagramType":"array","values":[...]} | {"diagramType":"graph","nodes":[{"id","label"}],"edges":[{"from","to"}],"directed"?} | {"diagramType":"mermaid","code":"<first line declares the type: sequenceDiagram/stateDiagram-v2/classDiagram/erDiagram/architecture-beta/timeline/quadrantChart>"}.
If the concept IS a linked structure (tree/graph/list), draw diagramType "graph" with its REAL nodes/edges. Curves of quantities are NOT diagrams — they belong to renderHint "chart".`,
  image: 'content is {"url": <the imageId EXACTLY as given in availableImages, e.g. "fig_003" — unknown ids are DELETED>, "alt": "...", "caption"?: "...", "page"?: <number>, "annotations"?: ordered teaching marks [{"verb":"encircle|arrow|underline|highlight|pointer|label","bbox":{"x","y","w","h" all 0-1},"text"?}]}.',
  manipulable: `content is {"param":{"id","label","min","max","step","default","unit"?},"xAxis":{"label","min","max"},"yAxis":{"label","min","max"},"curves":[{"id","label","formula":"linear|quadratic|sigmoid|expDecay","coeffs":{...numbers, with EXACTLY the coefficient the student controls set to "@param"},"style"?:"solid|dashed|ghost"}],"readout"?:{"label","formula","coeffs","at":<x>,"unit"?},"predict"?:{"prompt","choices":["..."],"answerIndex"}}.
The student DRAGS param and the curve recomputes LIVE from the engine's own formula — use it when the scene's core idea IS "what happens when X changes" (learning rate, price, coefficient, steepness). Choose axes that hold the curve across the WHOLE param range. ALWAYS include "predict" (commit-before-reveal). Formula coefficients: linear m,b · quadratic a,b,c · sigmoid k,x0 · expDecay A,k. A comparison baseline may stay as a fixed "ghost" curve. NEVER use this for static curves — that is renderHint "chart".`,
});
